Add dataset.ini config file for model finetuning
zacc/ssi-bot pull request #19
Opened 2021-08-10 22:13 UTC by the-sink

Changes `download_reddit_finetuning_data.py` and `output_finetuning_data.py` to use config variables assigned in `dataset.ini` as opposed to hard-coded parameters in the scripts themselves (#16)

2021-08-16 08:00 UTC, zacc requested changes

2021-08-16 10:03 UTC, the-sink commented on model_finetuning/dataset_template.ini
> +subreddits=test
Fixed (424c5ff)

2021-08-16 10:04 UTC, the-sink commented on model_finetuning/download_reddit_finetuning_data.py
> +	if config['DEFAULT']['submission_limit']:
Not sure how I missed that... 424c5ff

2021-08-16 10:04 UTC, the-sink commented on model_finetuning/download_reddit_finetuning_data.py
> +		submission_limit = config['DEFAULT']['submission_limit']
Fixed (424c5ff)

2021-08-17 03:26 UTC, zacc approved these changes
Nice work!

2021-08-17 03:26 UTC, merged