Add train.py script for local model training
zacc/ssi-bot pull request #23
Opened 2021-08-16 02:20 UTC by the-sink

This script is essentially a clone of the training code in the colab instance, but with a few variables pushed to the top and the addition of a `use_gpu` variable. Setting it to false disables `use_cuda` and `use_multiprocessing`, making training very slow, but it should allow many more people to use local training if they'd like. Also edited the bot label to pull the current date/time automatically and append the local time to the end. Addresses #20.

2021-08-16 08:01 UTC, zacc requested changes

2021-08-16 09:52 UTC, the-sink commented on model_finetuning/train.py
> +currentDateTime = datetime.now()
Replaced with `current_date_time` (27e691a)

2021-08-16 09:53 UTC, the-sink commented on model_finetuning/train.py
> +		"mlm": False, # has to be false for gpt-2
Fixed (27e691a)

2021-08-17 03:31 UTC, zacc commented on model_finetuning/train.py
> +		"best_model_dir": f"{bot_label}/best_model",
Sorry, we missed this indent!

2021-08-17 04:16 UTC, the-sink commented on model_finetuning/train.py
> +		"best_model_dir": f"{bot_label}/best_model",
Whoops, fixed 1835a94

2021-08-20 06:30 UTC, zacc commented
I didn't try and run it locally but the code looks right :shrug:

2021-08-20 06:30 UTC, merged